spring:
  application:
    name: Electricity Billing

  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;database=electricity;loginTimeout=30;sendStringParametersAsUnicode=false;encrypt=false
    username: electricity_login
    password: not@dm1n

  jpa:
    database: SQL_SERVER
    hibernate:
      ddl-auto: none
      format_sql: true
      show_sql: false
    show-sql: true

  flyway:
    enabled: true
    validate-on-migrate: false
    out-of-order: true
    user: electricity_login
    password: not@dm1n

server:
  port: 8080

logging:
  level:
    ROOT: INFO